export interface Publication {
    authors: string[];
    title: string;
    journal?: string;
    publisher?: string;
    volume?: string;
    number?: string;
    pages?: string;
    year: number;
    pdf?: string;
    doi?: string;
}

export const publications: Publication[] = [
    {
        authors: ["Derek Aguiar", "Wendy SW Wong", "Sorin Istrail"],
        title: "Tumor haplotype assembly algorithms for cancer genomics",
        journal: "Pacific Symposuium on Biocomputing",
        year: 2014,
        volume: "19",
        pages: "3-14",
        pdf: "http://www.worldscientific.com/doi/pdf/10.1142/9789814583220_0002",
    },
    {
        authors: ["Derek Aguiar", "Eric Morrow", "Sorin Istrail"],
        title: "Tractatus: an exact and subquadratic algorithm for inferring identity-by-descent multi-shared haplotype tracts",
        journal: "RECOMB",
        year: 2014,
        pages: "158-173",
        pdf: "https://link.springer.com/chapter/10.1007/978-3-319-05269-4_1",
    },
    {
        authors: [
            "Ece D Gamsiz",
            "Emma W Viscidi",
            "Abbie M Frederick",
            "Shailender Nagpal",
            "Stephan J Sanders",
            "Michael T Murtha",
            "Michael Schmidt",
            "Elizabeth W Triche",
            "Daniel H Geschwind",
            "Matthew W State",
            "others",
        ],
        title: "Intellectual Disability Is Associated with Increased Runs of Homozygosity in Simplex Autism",
        journal: "American Journal of Human Genetics",
        volume: "vol. 93, no. 1, pp. 103-109",
        year: 2013,
        doi: "https://doi.org/10.1016/j.ajhg.2013.06.004",
    },
    {
        authors: [
            "Alper Uzun",
            "Andrew T. Dewan",
            "Sorin Istrail",
            "James F. Padbury",
        ],
        title: "Pathway-based genetic analysis of preterm birth",
        journal: "Genomics",
        volume: "101",
        number: "3",
        pages: "163-170",
        year: 2013,
        pdf: "http://www.sciencedirect.com/science/article/pii/S0888754312002455",
        doi: "http://dx.doi.org/10.1016/j.ygeno.2012.12.005",
    },
    {
        authors: ["Sarah Tulin", "Derek Aguiar", "Sorin Istrail", "Joel Smith"],
        title: "A quantitative reference transcriptome for Nematostella vectensis early embryonic development: a pipeline for de novo assembly in emerging model systems",
        journal: "EvoDevo",
        volume: "4",
        number: "16",
        year: 2013,
        pdf: "http://www.evodevojournal.com/content/4/1/16/abstract",
    },
    {
        authors: ["Derek Aguiar", "Sorin Istrail"],
        title: "Haplotype assembly in polyploid genomes and identical by descent shared tracts",
        journal: "Bioinformatics",
        volume: "29",
        number: "13",
        pages: "i352-i360",
        year: 2013,
        pdf: "http://bioinformatics.oxfordjournals.org/content/29/13/i352.abstract",
        doi: "http://dx.doi.org/10.1093/bioinformatics/btt213",
    },
    {
        authors: ["Derek Aguiar", "Sorin Istrail"],
        title: "HAPCOMPASS: A fast cycle basis algorithm for accurate haplotype assembly of sequence data",
        journal: "Journal of Computational Biology",
        volume: "19",
        number: "6",
        pages: "577-590",
        year: 2012,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/hapcompass_jcb_draft.pdf",
        doi: "http://dx.doi.org/doi:10.1089/cmb.2012.0084",
    },
    {
        authors: [
            "Alper Uzun",
            "Alyse Laliberte",
            "Jeremy Parker",
            "Caroline Andrew",
            "Emily Winterrowd",
            "Surendra Sharma",
            "Sorin Istrail",
            "James F. Padbury",
        ],
        title: "dbPTB: a database for preterm birth",
        journal: "Database (Oxford)",
        volume: "2012",
        pages: "bar069",
        year: 2012,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/bar069.pdf",
        doi: "http://dx.doi.org/10.1093/database/bar069",
    },
    {
        authors: [
            "Hagit Shatkay",
            "Ramya Narayanaswamy",
            "Santosh Nagaral",
            "Na Harrington",
            "Dorothea Blostein",
            "Ryan Tarpine",
            "Kyle Schutter",
            "Rohith Mv",
            "Gowri Somanath",
            "Sorin Istrail",
            "Chandra Kambahmettu",
        ],
        title: "OCR-based Image Features for Biomedical Image and Article Classification: Identifying Documents Relevant to Cis-Regulatory Elements",
        journal: "ACM BCB",
        year: 2012,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/ACMBCB2012SubmitCameraReady.pdf",
    },
    {
        authors: ["Sorin Istrail"],
        title: "Computer Science Through Urn Games: An Unified Framework for a Hierarchy of Solvable and Unsolvable Problems",
        journal: "Proceedings of the Turing Centenary Conference",
        year: 2012,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/CS Through Urn Games - An Unified Approach.pdf",
    },
    {
        authors: ["Sorin Istrail", "Solomon Marcus"],
        title: "Turing and von Neumann's Brains and their Computers",
        journal: "Proceedings of the Turing Centenary Conference",
        year: 2012,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/Istrail-Marcus012912FINAL.pdf",
    },
    {
        authors: [
            "Austin Huang",
            "Joseph W Hogan",
            "Sorin Istrail",
            "Allison DeLong",
            "David A Katzenstein",
            "Rami Kantor",
        ],
        title: "Global analysis of sequence diversity within HIV-1 subtypes across geographic regions",
        journal: "Future Virology",
        volume: "7",
        number: "5",
        pages: "505-517",
        year: 2012,
        pdf: "http://www.futuremedicine.com/action/showCitFormats?doi=10.2217%2Ffvl.12.37",
    },
    {
        authors: ["Leon N Cooper", "Sorin Istrail"],
        title: "Mental Experience and the Turing Test: This Double Face is the Face of Mathematics",
        journal: "Proceedings of the Turing Centenary Conference",
        year: 2012,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/Cooper-Istrail012912FINAL.pdf",
    },
    {
        authors: [
            "Derek Aguiar",
            "Bjarni V. Halldorsson",
            "Eric M. Morrow",
            "Sorin Istrail",
        ],
        title: "DELISHUS: an efficient and exact algorithm for genome-wide detection of deletion polymorphism in autism",
        journal: "Bioinformatics",
        volume: "28",
        number: "12",
        pages: "i154-i162",
        year: 2012,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/Aguiar.245.pdf",
        doi: "http://dx.doi.org/10.1093/bioinformatics/bts234",
    },
    {
        authors: ["Ryan Tarpine", "Fumei Lam", "Sorin Istrail"],
        title: "Conservative Extensions of Linkage Disequilibrium Measures from Pairwise to Multi-loci and Algorithms for Optimal Tagging SNP Selection",
        journal: "Research in Computational Molecular Biology",
        publisher: "Springer Berlin / Heidelberg",
        volume: "6577",
        pages: "468-482",
        year: 2011,
        pdf: "http://dx.doi.org/10.1007/978-3-642-20036-6_42",
    },
    {
        authors: [
            "Austin Huang",
            "Rami Kantor",
            "Allison DeLong",
            "Leeann Schreier",
            "Sorin Istrail",
        ],
        title: "QColors: An algorithm for conservative viral quasispecies reconstruction from short and non-contiguous next generation sequencing reads",
        journal: "BIBM Workshops",
        publisher: "IEEE",
        pages: "130-136",
        year: 2011,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/06112365.pdf",
    },
    {
        authors: [
            "Bjarni Halldorsson",
            "Derek Aguiar",
            "Ryan Tarpine",
            "Sorin Istrail",
        ],
        title: "The Clark Phaseable Sample Size Problem: Long-Range Phasing and Loss of Heterozygosity in GWAS",
        journal: "Journal of Computational Biology",
        volume: "18",
        number: "3",
        pages: "323-333",
        year: 2011,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/clarkphaseablejournal.pdf",
        doi: "http://dx.doi.org/citeulike-article-id:9029749",
    },
    {
        authors: ["Bjarni Halldorsson", "Derek Aguiar", "Sorin Istrail"],
        title: "Haplotype phasing by multi-assembly of shared haplotypes: phase-dependent interactions between rare variants",
        journal: "Pac Symp Biocomput.",
        pages: "88-99",
        year: 2011,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/9789814335058_0010.pdf",
        doi: "http://dx.doi.org/citeulike-article-id:10540409",
    },
    {
        authors: [
            "Jongmin Nam",
            "Ping Dong",
            "Ryan Tarpine",
            "Sorin Istrail",
            "Eric H. Davidson",
        ],
        title: "Functional cis-regulatory genomics for systems biology",
        journal: "Proceedings of the National Academy of Sciences",
        volume: "107",
        number: "8",
        pages: "3930-3935",
        year: 2010,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/PNAS-2010-Nam-3930-5.pdf",
        doi: "http://dx.doi.org/10.1073/pnas.1000147107",
    },
    {
        authors: ["Fumei Lam", "Ryan Tarpine", "Sorin Istrail"],
        title: "The Imperfect Ancestral Recombination Graph Reconstruction Problem: Upper Bounds for Recombination and Homoplasy",
        journal: "Journal of Computational Biology",
        volume: "17",
        number: "6",
        pages: "767-781",
        year: 2010,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/impancestralrecomb.pdf",
    },
    {
        authors: [
            "Sorin Istrail",
            "Ryan Tarpine",
            "Kyle Schutter",
            "Derek Aguiar",
        ],
        title: "Practical Computational Methods for Regulatory Genomics: A cisGRN-Lexicon and cisGRN-Browser for Gene Regulatory Networks",
        journal: "Computational Biology of Transcription Factor Binding",
        publisher: "Humana Press",
        volume: "674",
        pages: "369-399",
        year: 2010,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/praccompmethods.pdf",
        doi: "http://dx.doi.org/citeulike-article-id:10540401",
    },
    {
        authors: [
            "Bjarni Halldorsson",
            "Derek Aguiar",
            "Ryan Tarpine",
            "Sorin Istrail",
        ],
        title: "The Clark Phase-able Sample Size Problem: Long-Range Phasing and Loss of Heterozygosity in GWAS",
        journal: "RECOMB",
        volume: "6044",
        pages: "158-173",
        year: 2010,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/clarkphaseable.pdf",
        doi: "http://dx.doi.org/citeulike-article-id:10541015",
    },
    {
        authors: [
            "Sorin Istrail",
            "Smadar Ben-Tabou De-Leon",
            "Eric H. Davidson",
        ],
        title: "The regulatory genome and the computer",
        journal: "Developmental Biology",
        volume: "310",
        number: "2",
        pages: "187-195",
        year: 2007,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/1-s2.0-S0012160607012547-main.pdf",
        doi: "http://dx.doi.org/10.1016/j.ydbio.2007.08.009",
    },
    {
        authors: [
            "Manoj P. Samanta",
            "Waraporn Tongprasit",
            "Sorin Istrail",
            "R. Andrew Cameron",
            "Qiang Tu",
            "Eric H. Davidson",
            "Viktor Stolc",
        ],
        title: "The Transcriptome of the Sea Urchin Embryo",
        journal: "Science",
        volume: "314",
        number: "5801",
        pages: "960-962",
        year: 2006,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/transcSeaUrchin.pdf",
        doi: "http://dx.doi.org/10.1126/science.1131898",
    },
    {
        authors: ["Bjarni V Halldorsson", "Roded Sharan", "Sorin Istrail"],
        title: "Islands of Tractability for Parsimony Haplotyping",
        journal: "Stanford Computational Systems Biology",
        year: 2006,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/10.1.1.86.9375.pdf",
    },
    {
        authors: [
            "Sea Urchin Genome Sequencing Consortium",
            "Erica Sodergren",
            "George M. Weinstock",
            "Eric H Davidson",
            "R. Andrew Cameron",
            "Richard A. Gibbs",
            "Robert C. Angerer",
            "Lynne M. Angerer",
            "Maria Ina Arnone",
            "David R. Burgess",
            "Robert D. Burke",
            "James A. Coffman",
            "Michael Dean",
            "Maurice R. Elphick",
            "Charles A. Ettensohn",
            "Kathy R. Foltz",
            "Amro Hamdoun",
            "Richard O. Hynes",
            "William H. Klein",
            "William Marzluff",
            "David R. McClay",
            "Robert L. Morris",
            "Arcady Mushegian",
            "Jonathan P. Rast",
            "L. Courtney Smith",
            "Michael C. Thorndyke",
            "Victor D. Vacquier",
            "Gary M. Wessel",
            "Greg Wray",
            "Lan Zhang",
            "Christine G. Elsik",
            "Olga Ermolaeva",
            "Wratko Hlavina",
            "Gretchen Hofmann",
            "Paul Kitts",
            "Melissa J. Landrum",
            "Aaron J. Mackey",
            "Donna Maglott",
            "Georgia Panopoulou",
            "Albert J. Poustka",
            "Kim Pruitt",
            "Victor Sapojnikov",
            "Xingzhi Song",
            "Alexandre Souvorov",
            "Victor Solovyev",
            "Zheng Wei",
            "Charles A. Whittaker",
            "Kim Worley",
            "K. James Durbin",
            "Yufeng Shen",
            "Olivier Fedrigo",
            "David Garfield",
            "Ralph Haygood",
            "Alexander Primus",
            "Rahul Satija",
            "Tonya Severson",
            "Manuel L. Gonzalez-Garay",
            "Andrew R. Jackson",
            "Aleksandar Milosavljevic",
            "Mark Tong",
            "Christopher E. Killian",
            "Brian T. Livingston",
            "Fred H. Wilt",
            "Nikki Adams",
            "Robert Bell",
            "Seth Carbonneau",
            "Rocky Cheung",
            "Patrick Cormier",
            "Bertrand Cosson",
            "Jenifer Croce",
            "Antonio Fernandez-Guerra",
            "Anne-Marie Genevire",
            "Manisha Goel",
            "Hemant Kelkar",
            "Julia Morales",
            "Odile Mulner-Lorillon",
            "Anthony J. Robertson",
            "Jared V. Goldstone",
            "Bryan Cole",
            "David Epel",
            "Bert Gold",
            "Mark E. Hahn",
            "Meredith Howard-Ashby",
            "Mark Scally",
            "John J. Stegeman",
            "Erin L. Allgood",
            "Jonah Cool",
            "Kyle M. Judkins",
            "Shawn S. McCafferty",
            "Ashlan M. Musante",
            "Robert A. Obar",
            "Amanda P. Rawson",
            "Blair J. Rossetti",
            "Ian R. Gibbons",
            "Matthew P. Hoffman",
            "Andrew Leone",
            "Sorin Istrail",
            "Stefan C. Materna",
            "Manoj P. Samanta",
            "Viktor et al. Stolc",
        ],
        title: "The Genome of the Sea Urchin Strongylocentrotus purpuratus",
        journal: "Science",
        volume: "314",
        number: "5801",
        pages: "941-952",
        year: 2006,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/sci.pdf",
        doi: "http://dx.doi.org/10.1126/science.1133609",
    },
    {
        authors: ["Sorin Istrail", "Eric Davidson"],
        title: "Logic functions of the genomic cis-regulatory code",
        journal: "Proceedings of the National Academy of Sciences",
        volume: "102",
        number: "14",
        pages: "4954-4959",
        year: 2005,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/PNAS-2005-Istrail-4954-9.pdf",
    },
    {
        authors: [
            "Liliana Florea",
            "Valentina Di Francesco",
            "Jason Miller",
            "Russell Turner",
            "Alison Yao",
            "Michael Harris",
            "Brian Walenz",
            "Clark Mobarry",
            "Gennady V. Merkulov",
            "Rosane Charlab",
            "Ian Dew",
            "Zuoming Deng",
            "Sorin Istrail",
            "Peter Li",
            "Granger Sutton",
        ],
        title: "Gene and alternative splicing annotation with AIR",
        journal: "Genome Research",
        volume: "15",
        number: "1",
        pages: "54-66",
        year: 2005,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/Genome Res.-2005-Florea-54-66.pdf",
    },
    {
        authors: [
            "Francisco M. De La Vega",
            "Hadar Isaac",
            "Andrew Collins",
            "Charles R. Scafe",
            "Bjarni V. Halldorsson",
            "Xiaoping Su",
            "Ross A. Lippert",
            "Yu Wang",
            "Marion Laig-Webster",
            "Ryan T. Koehler",
            "Janet S. Ziegle",
            "Lewis T. Wogan",
            "Junko F. Stevens",
            "Kyle M. Leinen",
            "Sheri J. Olson",
            "Karl J. Guegler",
            "Xiaoqing You",
            "Lily H. Xu",
            "Heinz G. Hemken",
            "Francis Kalush",
            "Mitsuo Itakura",
            "Yi Zheng",
            "Guy de Thò",
            "Stephen J. O'Brien",
            "Andrew G. Clark",
            "Sorin Istrail",
            "Michael W. Hunkapiller",
            "Eugene G. Spier",
            "Dennis A. Gilbert",
        ],
        title: "The linkage disequilibrium maps of three human chromosomes across four populations reflect their demographic history and a common underlying recombination pattern",
        journal: "Genome Research",
        volume: "15",
        number: "4",
        pages: "454-462",
        year: 2005,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/Genome Res.-2005-De La Vega-454-62.pdf",
    },
    {
        authors: [
            "Ross Lippert",
            "Xiaoyue Zhao",
            "Liliana Florea",
            "Clark Mobarry",
            "Sorin Istrail",
        ],
        title: "Finding anchors for genomic sequence comparison",
        journal:
            "8th Annual International Conference on Research in Computational Biology (RECOMB04)",
        publisher: "ACM Press",
        year: 2004,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/findingAnchors.pdf",
    },
    {
        authors: [
            "Sorin Istrail",
            "Granger G. Sutton",
            "Liliana Florea",
            "Aaron L. Halpern",
            "Clark M. Mobarry",
            "Ross Lippert",
            "Brian Walenz",
            "Hagit Shatkay",
            "Ian Dew",
            "Jason R. Miller",
            "Michael J. Flanigan",
            "Nathan J. Edwards",
            "Randall Bolanos",
            "Daniel Fasulo",
            "Bjarni V. Halldorsson",
            "Sridhar Hannenhalli",
            "Russell Turner",
            "Shibu Yooseph",
            "Fu Lu",
            "Deborah R. Nusskern",
            "Bixiong Chris Shue",
            "Xiangqun Holly Zheng",
            "Fei Zhong",
            "Arthur L. Delcher",
            "Daniel H. Huson",
            "Saul A. Kravitz",
            "Laurent Mouchard",
            "Knut Reinert",
            "Karin A. Remington",
            "Andrew G. Clark",
            "Michael S. Waterman",
            "Evan E. Eichler",
            "Mark D. Adams",
            "Michael W. Hunkapiller",
            "Eugene W. Myers",
            "J. Craig Venter",
        ],
        title: "Whole Genome Shotgun Assembly and Comparison of Human Genome Assemblies",
        journal: "Proceedings of the National Academy of Sciences",
        volume: "101",
        number: "7",
        pages: "1916-1921",
        year: 2004,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/PNAS-2004-Istrail-1916-21.pdf",
    },
    {
        authors: [
            "Sorin Istrail",
            "Liliana Florea",
            "Bjarni V Halldorsson",
            "Oliver Kohlbacher",
            "Russell Schwartz",
            "Von Bing Yap",
            "Jonathan Yewdell",
            "Stephen Hoffman",
        ],
        title: "Comparative Immuno-Peptidomics of Humans and their Pathogens",
        journal: "Proceedings of the National Academy of Sciences",
        volume: "101",
        number: "36",
        pages: "13268-13272",
        year: 2004,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/PNAS-2004-Istrail-13268-72.pdf",
    },
    {
        authors: [
            "Bjarni V Halldorsson",
            "Vineet Bafna",
            "Ross Lippert",
            "Russell Schwartz",
            "Francisco M. De La Vega",
            "Andrew G. Clark",
            "Sorin Istrail",
        ],
        title: "Optimal haplotype block free selection of tagging SNPs for genome-wide association studies",
        journal: "Genome Research",
        volume: "14",
        number: "8",
        pages: "1633-1640",
        year: 2004,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/Genome Res.-2004-Halldorsson-1633-40.pdf",
    },
    {
        authors: [
            "Alberto Caprara",
            "Robert Carr",
            "Sorin Istrail",
            "Giuseppe Lancia",
            "Brian Walenz",
        ],
        title: "1001 optimal PDB structure alignments: integer programming methods for finding the maximum contact map overlap",
        journal: "Journal of Computational Biology",
        volume: "11",
        number: "1",
        pages: "27-52",
        year: 2004,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/1001-JCB.pdf",
        doi: "http://dx.doi.org/citeulike-article-id:165612",
    },
    {
        authors: [
            "Russell Schwartz",
            "Bjarni V Halldorsson",
            "Vineet Bafna",
            "Andrew G. Clark",
            "Sorin Istrail",
        ],
        title: "Robustness of Inference of Haplotype Block Structure",
        journal: "Journal of Computational Biology",
        year: 2003,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/jcb-03.pdf",
    },
    {
        authors: ["Russell Schwartz", "Andrew G. Clark", "Sorin Istrail"],
        title: "Inferring Piecewise Ancestral History from Haploid Sequences",
        journal:
            "First RECOMB Satellite on Computational Methods for SNPs and Haplotype Inference, (RECOMB SNP&HAP03)",
        publisher: "Springer",
        year: 2003,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/infpiecewise.pdf",
    },
    {
        authors: [
            "Bjarni V Halldorsson",
            "Vineet Bafna",
            "Nathan J. Edwards",
            "Ross Lippert",
            "Shibu Yooseph",
            "Sorin Istrail",
        ],
        title: "A survey of computational methods for determining haplotypes",
        journal:
            "First RECOMB Satellite on Computational Methods for SNPs and Haplotype Inference, (RECOMB SNP&HAP03)",
        publisher: "Springer",
        pages: "26-47",
        year: 2003,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/IstrailSurvey.pdf",
    },
    {
        authors: [
            "Bjarni V Halldorsson",
            "Vineet Bafna",
            "Nathan J. Edwards",
            "Ross Lippert",
            "Shibu Yooseph",
            "Sorin Istrail",
        ],
        title: "Combinatorial problems arising in SNP and haplotype analysis",
        journal:
            "Fourth International Conference on Discrete Mathematics and Theoretical Computer Science, (CDMTCS03)",
        publisher: "Springer",
        pages: "26-47",
        year: 2003,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/10.1.1.123.4929.pdf",
    },
    {
        authors: [
            "Liliana Florea",
            "Bjarni V Halldorsson",
            "Oliver Kohlbacher",
            "Russell Schwartz",
            "Stephen Hoffman",
            "Sorin Istrail",
        ],
        title: "Epitope prediction algorithms for peptide-based vaccine design",
        journal:
            "Second Annual IEEE Computer Society Bioinformatics Conference (CSB03)",
        publisher: "IEEE Press",
        pages: "17-26",
        year: 2003,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/paper119.pdf",
    },
    {
        authors: [
            "Liliana Florea",
            "Bjarni V Halldorsson",
            "Oliver Kohlbacher",
            "Russell Schwartz",
            "Stephen Hoffman",
            "Sorin Istrail",
        ],
        title: "A Computational Pipeline for High-Throughput T-Cell Epitope Prediction",
        publisher: "Celera Genomics",
        year: 2003,
    },
    {
        authors: [
            "Vineet Bafna",
            "Bjarni V Halldorsson",
            "Russell Schwartz",
            "Andrew G. Clark",
            "Sorin Istrail",
        ],
        title: "Haplotypes and Informative SNP Selection Algorithms: Don't Block Out Information",
        journal:
            "7th Annual International Conference on Computational Molecular Biology (RECOMB03)",
        publisher: "ACM Press",
        pages: "19-27",
        year: 2003,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/informativeSNP.pdf",
    },
    {
        authors: ["Russell Schwartz", "Andrew G. Clark", "Sorin Istrail"],
        title: "Methods for inferring block-wise ancestral history from haploid sequences: The haplotype coloring problem",
        journal: "2nd Workshop on Algorithms in Bioinformatics, (WABI02)",
        publisher: "Springer",
        pages: "44-59",
        year: 2002,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/methodsinfblock.pdf",
    },
    {
        authors: [
            "Romeo Rizzi",
            "Vineet Bafna",
            "Sorin Istrail",
            "Giuseppe Lancia",
        ],
        title: "Practical Algorithms and Fixed-Parameter Tractability for the Single Individual SNP Haplotyping Problem",
        journal: "2nd Workshop on Algorithms in Bioinformatics, (WABI02)",
        publisher: "Springer",
        pages: "29-43",
        year: 2002,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/pracAlgsSnpHaplo.pdf",
    },
    {
        authors: [
            "Ross Lippert",
            "Russell Schwartz",
            "Giuseppe Lancia",
            "Sorin Istrail",
        ],
        title: "Algorithmic Strategies for the SNP Haplotype Assembly Problem",
        journal: "Briefings in Bioinformatics",
        volume: "3",
        number: "1",
        pages: "1-9",
        year: 2002,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/Brief Bioinform-2002-Lippert-23-31.pdf",
    },
    {
        authors: ["Sorin Istrail"],
        title: "The Haplotype Phasing Problem",
        publisher: "Celera Genomics",
        year: 2002,
    },
    {
        authors: [
            "J. Craig Venter",
            "Mark D. Adams",
            "Eugene W. Myers",
            "Peter W. Li",
            "Richard J. Mural",
            "Granger G. Sutton",
            "Hamilton O. Smith",
            "Mark Yandell",
            "Cheryl A. Evans",
            "Robert A. Holt",
            "Jeannine D. Gocayne",
            "Peter Amanatides",
            "Richard M. Ballew",
            "Daniel H. Huson",
            "Jennifer Russo Wortman",
            "Qing Zhang",
            "Chinnappa D. Kodira",
            "Xiangqun H. Zheng",
            "Lin Chen",
            "Marian Skupski",
            "Gangadharan Subramanian",
            "Paul D. Thomas",
            "Jinghui Zhang",
            "George L. Gabor Miklos",
            "Catherine Nelson",
            "Samuel Broder",
            "Andrew G. Clark",
            "Joe Nadeau",
            "Victor A. McKusick",
            "Norton Zinder",
            "Arnold J. Levine",
            "Richard J. Roberts",
            "Mel Simon",
            "Carolyn Slayman",
            "Michael Hunkapiller",
            "Randall Bolanos",
            "Arthur Delcher",
            "Ian Dew",
            "Daniel Fasulo",
            "Michael Flanigan",
            "Liliana Florea",
            "Aaron Halpern",
            "Sridhar Hannenhalli",
            "Saul Kravitz",
            "Samuel Levy",
            "Clark Mobarry",
            "Knut Reinert",
            "Karin Remington",
            "Jane Abu-Threideh",
            "Ellen Beasley",
            "Kendra Biddick",
            "Vivien Bonazzi",
            "Rhonda Brandon",
            "Michele Cargill",
            "Ishwar Chandramouliswaran",
            "Rosane Charlab",
            "Kabir Chaturvedi",
            "Zuoming Deng",
            "Valentina Di Francesco",
            "Patrick Dunn",
            "Karen Eilbeck",
            "Carlos Evangelista",
            "Andrei E. Gabrielian",
            "Weiniu Gan",
            "Wangmao Ge",
            "Fangcheng Gong",
            "Zhiping Gu",
            "Ping Guan",
            "Thomas J. Heiman",
            "Maureen E. Higgins",
            "Rui-Ru Ji",
            "Zhaoxi Ke",
            "Karen A. Ketchum",
            "Zhongwu Lai",
            "Yiding Lei",
            "Zhenya Li",
            "Jiayin Li",
            "Yong Liang",
            "Xiaoying Lin",
            "Fu Lu",
            "Gennady V. Merkulov",
            "Natalia Milshina",
            "Helen M. Moore",
            "Ashwinikumar K Naik",
            "Vaibhav A. Narayan",
            "Beena Neelam",
            "Deborah Nusskern",
            "Douglas B. Rusch",
            "Steven Salzberg",
            "Wei Shao",
            "Bixiong Shue",
            "Jingtao Sun",
            "Zhen Yuan Wang",
            "Aihui Wang",
            "Xin Wang",
            "Jian Wang",
            "Ming-Hui Wei",
            "Ron Wides",
            "Chunlin Xiao",
            "Chunhua et al. Yan",
        ],
        title: "The Sequence of the Human Genome",
        journal: "Science",
        volume: "291",
        number: "5507",
        pages: "1304-1351",
        year: 2001,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/Science_2001_VenterThe_sequence_of_the_human.pdf",
    },
    {
        authors: [
            "Russell J. Turner",
            "Kabir Chaturvedi",
            "Nathan J. Edwards",
            "Daniel Fasulo",
            "Aaron L. Halpern",
            "Daniel H. Huson",
            "Oliver Kohlbacher",
            "Jason R. Miller",
            "Knut Reinert",
            "Karin A. Remington",
            "Russell Schwartz",
            "Brian Walenz",
            "Shibu Yooseph",
            "Sorin Istrail",
        ],
        title: "Visualization challenges for a new cyberpharmaceutical computing paradigm",
        journal:
            "IEEE 2001 symposium on parallel and large-data visualization and graphics",
        publisher: "IEEE Press",
        pages: "7-18",
        year: 2001,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/p7-turner.pdf",
    },
    {
        authors: ["Russell Schwartz", "Sorin Istrail", "Jonathan King"],
        title: "Frequencies of amino-acid strings in globular proteins sequences indicate suppression of blocks of consecutive hydrophobic residues",
        journal: "Protein Science",
        volume: "10",
        pages: "1023-1031",
        year: 2001,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/101023_ftp.pdf",
    },
    {
        authors: [
            "M. Li",
            "Ross Lippert",
            "Russell Schwartz",
            "Michael Waterman",
            "Sorin Istrail",
        ],
        title: "Haplotype Reconstruction from SNP Alignment",
        publisher: "Celera Genomics",
        year: 2001,
    },
    {
        authors: [
            "Giuseppe Lancia",
            "Robert Carr",
            "Brian Walenz",
            "Sorin Istrail",
        ],
        title: "101 Optimal PDB Structure Alignments: A Branch-and-Cut Algorithm for the Maximum Contact Map Overlap Problem",
        journal: "RECOMB",
        publisher: "ACM Press",
        pages: "201-211",
        year: 2001,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/101%20optimal.pdf",
    },
    {
        authors: [
            "Giuseppe Lancia",
            "Vineet Bafna",
            "Sorin Istrail",
            "Ross Lippert",
            "Russell Schwartz",
        ],
        title: "SNPs Problems: Complexity and Algorithms",
        journal: "EAS",
        publisher: "Springer",
        volume: "2161",
        pages: "182-193",
        year: 2001,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/snpproblems.pdf",
    },
    {
        authors: [
            "Sorin Istrail",
            "Alan Hurd",
            "Ross A. Lippert",
            "Brian Walenz",
            "Serafim Batzoglou",
            "John H. Conway",
            "Fredrick W. Peyerl",
        ],
        title: "Prediction of Self-Assembly of Energetic Tiles and Dominos: Experiments, Mathematics and Software",
        publisher: "Sandia Labs",
        year: 2000,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/10.1.1.134.9581.pdf",
    },
    {
        authors: ["Sorin Istrail"],
        title: "Statistical Mechanics, Three-Dimensionality and NP-Completeness: I. Universality of Intractability of the Partition Functions of the Ising Model Across Non-Planar Lattices",
        journal: "STOC",
        publisher: "ACM Press",
        pages: "87-96",
        year: 2000,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/p87-istrail.pdf",
    },
    {
        authors: [
            "Debbie Goldman",
            "Sorin Istrail",
            "Giuseppe Lancia",
            "Antonio Piccolboni",
            "Brian Walenz",
        ],
        title: "Algorithmic Strategies in Combinatorial Chemistry",
        journal: "SODA",
        publisher: "ACM Press",
        year: 2000,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/p275-goldman.pdf",
    },
    {
        authors: ["Russell Schwartz", "Sorin Istrail", "Jonathan King"],
        title: "Insights Into the Association of Partially Folded Chains Derived From Lattice Simulation Models",
        publisher: "Sandia Labs",
        year: 1999,
    },
    {
        authors: ["Ross A. Lippert", "Sorin Istrail", "Alan Hurd"],
        title: "Prediction of Energetic Tiles Self-Assembly",
        publisher: "Sandia Labs",
        year: 1999,
    },
    {
        authors: ["Sorin Istrail", "Russell Schwartz", "Jonathan King"],
        title: "Lattice Simulations of Aggregation Funnels of Protein Folding",
        journal: "Journal of Computational Biology",
        volume: "6",
        number: "2",
        year: 1999,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/latticesim.pdf",
    },
    {
        authors: [
            "Deborah Goldman",
            "Sorin Istrail",
            "Christos H. Papadimitriou",
        ],
        title: "Algorithmic Aspects of Protein Structure Similarity",
        journal: "FOCS",
        publisher: "IEEE Computer Society Press",
        year: 1999,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/00814624.pdf",
    },
    {
        authors: ["John H. Conway", "Sorin Istrail"],
        title: "Mathematics of Self-Assembly",
        publisher: "Sandia Labs",
        year: 1999,
    },
    {
        authors: ["Robert Carr", "Giuseppe Lancia", "Sorin Istrail"],
        title: "Branch-and-Bound LP-algorithms for Protein Structure Alignment Based on Contact Map Overlap",
        publisher: "Sandia Labs",
        year: 1999,
    },
    {
        authors: ["Serafim Batzoglou", "Sorin Istrail"],
        title: "Physical Mapping with Repeated Probes: The Hypergraph Superstring Problem",
        journal: "In 10th Conference on Combinatorial Pattern Matching (CPM99)",
        publisher: "Springer",
        year: 1999,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/Physical mapping with repeated probes.pdf",
    },
    {
        authors: ["Sorin Istrail", "R. Ravi"],
        title: "What is a Good Objective for Multiple Sequence Alignment?",
        journal: "Sandia Labs",
        year: 1998,
    },
    {
        authors: ["Sorin Istrail"],
        title: "Multiple Sequence Alignment and Voting Paradoxes",
        journal: "Sandia Labs",
        year: 1998,
    },
    {
        authors: ["William E. Hart", "Sorin Istrail"],
        title: "Robust Proofs of NP-Hardness for Protein Folding: General Lattices and Energy Potentials",
        journal: "In Journal of Computational Biology",
        year: 1997,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/robustproofs.pdf",
        volume: "4",
        number: "1",
        pages: "1-22",
    },
    {
        authors: ["William E. Hart", "Sorin Istrail"],
        title: "Lattice and Off-Lattice Side Chain Models of Protein Folding: Linear Time Structure Prediction Better than 86% of Optimal",
        journal:
            "In First International Conference on Computational Molecular Biology, (RECOMB97)",
        publisher: "ACM Press",
        year: 1997,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/1997/p137-hart.pdf",
        pages: "137-146",
    },
    {
        authors: ["Sorin Istrail"],
        title: "Approximations Algorithms on Matroids Based on Cycle-Bases and Applications",
        journal: "Sandia Labs",
        year: 1996,
    },
    {
        authors: ["William E. Hart", "Sorin Istrail"],
        title: "Fast Protein Folding in the Hydrophobic-Hydrophilic Model Within Three-eighths of Optimal",
        journal: "In Journal of Computational Biology",
        year: 1996,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/1995/hart-istrail-stoc95.pdf",
        volume: "3",
        number: "1",
        pages: "53-96",
    },
    {
        authors: ["William E. Hart", "Sorin Istrail"],
        title: "Invariant Patterns in Crystal Lattices: Implications for Protein Folding Algorithms",
        journal: "In 7th Conference on Combinatorial Pattern Matching (CPM96)",
        publisher: "Springer",
        year: 1996,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/fulltext.pdf",
        pages: "288-303",
    },
    {
        authors: ["William E. Hart", "Sorin Istrail"],
        title: "Fast Protein Folding in the Hydrophobic-Hydrophilic Model Within Three-eighths of Optimal",
        journal:
            "In 27th Annual ACM Symposium on Theory of Computation (STOC95)",
        publisher: "ACM Press",
        year: 1995,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/10.1.1.110.3139.pdf",
        pages: "157-168",
    },
    {
        authors: ["William E. Hart", "Sorin Istrail"],
        title: "Crystallographical universal approximation: A complexity theory of protein folding algorithms for crystal lattices",
        journal: "Sandia Labs",
        year: 1995,
    },
    {
        authors: ["David Greenberg", "Sorin Istrail"],
        title: "Physical Mapping by STS Hybridization: Algorithmic Strategies and the Challenge of Software Evaluation",
        journal: "In Journal of Computational Biology",
        year: 1995,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/10.1.1.50.8961.pdf",
        volume: "2",
        pages: "219-274",
    },
    {
        authors: ["Bard Bloom", "Sorin Istrail", "Albert R. Meyer"],
        title: "Bisimulation can't be traced",
        journal: "Journal of the ACM",
        volume: "42",
        number: "1",
        pages: "232-268",
        year: 1995,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/p232-bloom.pdf",
        doi: "10.1145/201019.201022",
    },
    {
        authors: ["Dejan Zivkovic", "Sorin Istrail"],
        title: "Bounded-width polynomial size Boolean formulas compute exactly those functions from AC^0",
        journal: "Information Processing Letters",
        volume: "50",
        number: "4",
        pages: "211-216",
        year: 1994,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/1-s2.0-0020019094000360-main.pdf",
        doi: "10.1016/0020-0190(94)00036-0",
    },
    {
        authors: ["David Greenberg", "Sorin Istrail"],
        title: "The Chimeric Mapping Problem: Algorithmic Strategies and Performance Evaluation on Synthetic Genomic Data",
        journal: "Computers and Chemistry",
        volume: "18",
        number: "3",
        pages: "207-220",
        year: 1994,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/The chimeric mapping problem.pdf",
        doi: "",
    },
    {
        authors: ["Sorin Istrail", "Dejan Zivkovic"],
        title: "A non-probabilistic switching lemma for the Sipser function",
        journal:
            "10th Annual Symposium on Theoretical Aspects of Computer Science (STACS93)",
        volume: "665",
        pages: "566-575",
        year: 1993,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/A non-probabilistic switching lemma for the Sipser function.pdf",
        doi: "",
    },
    {
        authors: ["Sorin Istrail"],
        title: "The Chimeric Clones Problem",
        publisher: "Sandia Labs",
        year: 1993,
        pdf: "",
        doi: "",
    },
    {
        authors: ["J Zipoli", "Sorin Istrail"],
        title: "On the impossibility of the crossover method for proving NP-completeness of the planar chromatic index problem",
        publisher: "Wesleyan University",
        year: 1991,
        pdf: "",
        doi: "",
    },
    {
        authors: ["Sorin Istrail"],
        title: "Constructing generalized universal traversing sequences of polynomial size for graphs of small diameter",
        journal:
            "31st Annual IEEE Symposium on Foundations of Computer Science (FOCS90)",
        pages: "439-448",
        year: 1990,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/00089564.pdf",
        doi: "",
    },
    {
        authors: ["Sorin Istrail"],
        title: "On the complexity of unpredictability",
        publisher: "Wesleyan University",
        year: 1990,
        pdf: "",
        doi: "",
    },
    {
        authors: ["Sorin Istrail"],
        title: "An arithmetical hierarchy in propositional dynamic logic",
        journal: "Information and Computation",
        volume: "81",
        number: "3",
        pages: "280-289",
        year: 1989,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/an arithmetical hierarchy in propositional dynamic logic.pdf",
        doi: "10.1016/0890-5401(89)90030-3",
    },
    {
        authors: ["Sorin Istrail"],
        title: "An algorithm for embedding planar graphs in six pages",
        journal: "Iasi University Annals, Mathematics-Computer Science",
        volume: "34",
        number: "4",
        pages: "329-341",
        year: 1988,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/1-s2.0-0304397582900809-main.pdf",
        doi: "10.1016/0304-3975(88)90063-5",
    },
    {
        authors: ["Sorin Istrail"],
        title: "Polynomial universal traversing sequences for cycles are constructible",
        journal: "20th Annual ACM Symposium on Theory of Computing (STOC88)",
        publisher: "ACM Press",
        pages: "453-491",
        year: 1988,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/p491-istrail.pdf",
    },
    {
        authors: ["Lenwood S. Heath", "Sorin Istrail"],
        title: "The pagenumber of genus g graphs is O(g)",
        journal: "19th Annual ACM Symposium on Theory of Computing (STOC87)",
        publisher: "ACM Press",
        pages: "388-397",
        year: 1987,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/TR-90-21.pdf",
    },
    {
        authors: ["Cristian Masalagiu", "Sorin Istrail"],
        title: "Nivat's processing systems: decision problems related to protection and synchronization",
        journal: "Theoretical Computer Science",
        volume: "26",
        pages: "83-103",
        year: 1983,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/1-s2.0-0304397583900804-main.pdf",
    },
    {
        authors: ["Cristian Masalagiu", "Sorin Istrail"],
        title: "On protection in Nivat processing systems",
        journal: "Colloquium of Automata and Programming (CAAP83)",
        publisher: "Springer",
        volume: "159",
        pages: "255-268",
        year: 1983,
    },
    {
        authors: ["Nguyen Xuan My", "Sorin Istrail"],
        title: "N-contextual schemes",
        journal: "Bulletin Mathematique",
        volume: "Tome 26 (74)",
        number: "3",
        pages: "241-249",
        year: 1982,
    },
    {
        authors: ["Sorin Istrail"],
        title: "Some remarks on non-algebraic adherences",
        journal: "Theoretical Computer Science",
        volume: "21",
        pages: "341-349",
        year: 1982,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/1-s2.0-0304397582900809-main.pdf",
    },
    {
        authors: ["Sorin Istrail"],
        title: "Generalizations of Ginsburg-Rice-Schutzenberger fixed-point theorem for context-sensitive and recursive-enumerable sets",
        journal: "Theoretical Computer Science",
        volume: "18",
        pages: "333-341",
        year: 1982,
    },
    {
        authors: ["Cristian Masalagiu", "Sorin Istrail"],
        title: "Decision problems for languages associated with protection of systems",
        journal: "Automatic Systems and Informatics",
        publisher: "Polytechnic Institute of Bucharest",
        pages: "306-312",
        year: 1981,
    },
    {
        authors: ["Sorin Istrail"],
        title: "On a linear theory of recursive-enumerable sets",
        journal: "Series in Mathematics",
        volume: "Inst. de Mat., vol. 38 Increst",
        pages: "20",
        year: 1981,
    },
    {
        authors: ["Sorin Istrail"],
        title: "Chomsky-Schutzenberger representations for families of languages and grammatical types",
        journal:
            "International Conference on Automata, Languages and Programming (ICALP81)",
        publisher: "Springer",
        volume: "115",
        pages: "333-347",
        year: 1981,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/chomsky-schut.pdf",
    },
    {
        authors: ["L Olaru", "Sorin Istrail"],
        title: "An efficient data-structure for computer-graphics",
        journal:
            "Artificial Intelligence and Information Control Systems of Robots",
        pages: "83-85",
        year: 1980,
    },
    {
        authors: ["Sorin Istrail"],
        title: "A fixed-point approach to contextual languages",
        journal: "Revue Roumaine de Mathematiques Pures et Appliquees",
        volume: "25",
        number: "6",
        pages: "861-869",
        year: 1980,
    },
    {
        authors: ["Sorin Istrail"],
        title: "On complements of some bounded context-sensitive languages",
        journal: "Information and Control",
        volume: "42",
        number: "3",
        pages: "283-289",
        year: 1979,
    },
    {
        authors: ["Sorin Istrail"],
        title: "On the complexity of program divergence",
        journal: "Foundations of Control Engineering",
        volume: "4",
        number: "1",
        pages: "19-26",
        year: 1979,
    },
    {
        authors: ["Sorin Istrail"],
        title: "A fixed-point theorem for recursive-enumerable languages and some considerations about semantics of monadic programs",
        journal:
            "International Conference on Automata, Languages and Programming (ICALP79)",
        publisher: "Springer",
        volume: "71",
        pages: "289-303",
        year: 1979,
        pdf: "http://www.brown.edu/Research/Istrail_Lab/papers/afixedpoint",
    },
    {
        authors: ["Sorin Istrail", "Dan Simovici"],
        title: "Computing grammars and context-sensitive languages",
        journal:
            "Revue Francais D'Automatique, Informatique et Recherche Operationelle",
        volume: "12",
        number: "1",
        pages: "33-48",
        year: 1978,
    },
    {
        authors: ["Sorin Istrail"],
        title: "Contextual grammars with regular choice",
        journal: "Studii si Cercetari Matematice",
        volume: "30",
        number: "3",
        pages: "287-294",
        year: 1978,
    },
    {
        authors: ["Sorin Istrail"],
        title: "A problem about contextual grammars with choice",
        journal: "Studii si Cercetari Matematice",
        volume: "30",
        number: "4",
        pages: "401-408",
        year: 1978,
    },
    {
        authors: ["Sorin Istrail"],
        title: "Elementary bounded languages",
        journal: "Information and Control",
        volume: "39",
        number: "2",
        pages: "177-191",
        year: 1978,
    },
    {
        authors: ["Sorin Istrail"],
        title: "On irreducible languages and nonrational numbers",
        journal: "Bulletin Mathematique",
        volume: "21",
        number: "3-4",
        pages: "301-308",
        year: 1977,
    },
    {
        authors: ["Sorin Istrail"],
        title: "On formal constructions of algebraic numbers of degree two",
        journal: "Revue Roumaine de Mathematiques Pures et Appliquees",
        volume: "22",
        number: "9",
        pages: "1235-1239",
        year: 1977,
    },
    {
        authors: ["Sorin Istrail"],
        title: "On the weak equivalence problem of OL-systems with some generative devices",
        journal: "Studii si Cercetari Matematice",
        volume: "23",
        number: "2",
        pages: "419-422",
        year: 1977,
    },
    {
        authors: ["Sorin Istrail"],
        title: "On some symmetric operators on free semigroups",
        journal: "Studii si Cercetari Matematice",
        volume: "28",
        number: "1",
        pages: "111-121",
        year: 1976,
    },
];
