name: Deploy to GitHub Pages & Remote Server

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job for GitHub Pages deployment
  build-github-pages:
    runs-on: ubuntu-latest
    env:
      ASTRO_SITE: "https://istrail-laboratory.github.io"
      ASTRO_BASE: "/"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install, build, and upload Astro site for GitHub Pages
        uses: withastro/action@v2

      - name: Upload primary site artifact
        uses: actions/upload-artifact@v4
        with:
          name: primary-site-build-${{ github.run_id }}
          path: dist

  # Build job for Remote Server deployment
  build-remote:
    runs-on: ubuntu-latest
    env:
      ASTRO_SITE: "https://cs.brown.edu/people/sistrail/"
      ASTRO_BASE: "/"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install, build, and upload Astro site for Remote Server
        uses: withastro/action@v2

      - name: Upload remote site artifact
        uses: actions/upload-artifact@v4
        with:
          name: remote-site-build-${{ github.run_id }}
          path: dist

  # Deploy to GitHub Pages using the primary build
  deploy-github-pages:
    needs: build-github-pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download primary site artifact
        uses: actions/download-artifact@v4
        with:
          name: primary-site-build-${{ github.run_id }}
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          folder: dist

  # Deploy to the Remote Server via rsync using the remote build
  deploy-remote:
    needs: build-remote
    runs-on: ubuntu-latest
    steps:
      - name: Download remote site artifact
        uses: actions/download-artifact@v4
        with:
          name: remote-site-build-${{ github.run_id }}
          path: dist

      - name: Deploy to Remote Server via rsync
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete --omit-dir-times
          path: dist/
          remote_path: ${{ vars.REMOTE_PATH }}
          remote_host: ${{ vars.REMOTE_HOST }}
          remote_user: ${{ vars.REMOTE_USER }}
          remote_key: ${{ secrets.DEPT_KEY }}
