name: Deploy to GitHub Pages and Remote Server

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false

      - name: Install dependencies
        run: bundle install --verbose

      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --source . --destination ./_site --baseurl "/courses/csci2840/spring-2025"

      # Upload the built site for later jobs
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: ./_site

  deploy-github-pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download site build
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site  # Make sure this matches the built Jekyll output

  deploy-remote:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download site build
        uses: actions/download-artifact@v4
        with:
          name: site-build
          path: _site

      - name: rsync files to remote server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete --omit-dir-times
          path: _site/
          remote_path: ${{ vars.REMOTE_PATH }}
          remote_host: ${{ vars.REMOTE_HOST }}
          remote_user: ${{ vars.REMOTE_USER }}
          remote_key: ${{ secrets.DEPT_KEY }}
